# Generated by Django 4.0.2 on 2022-02-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_rename_image_profile_picture_profile_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='text',
            new_name='bio',
        ),
    ]
